### ISSUE TITLE
Got JS error when I focus on a <a> link (with "linkNewTab": true)

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/redactor#132]
The 'Open on a new window' checkbox doesn’t save and more : If I checked it and click on the Source button, the `target="_blank"` disappears. 

I got this error everytime I focus on a link in my redactor fields :
`redactor.js:4741 Uncaught TypeError: (intermediate value)(intermediate value).setActive is not a function`

**My `.json` config**

```
{
    "buttons": [
	    "html",
        "format",
        "bold",
        "italic",
        "link",
        "lists",
        "horizontalrule"
    ],
    "formatting": [
    	"h2",
    	"h3",
    	"h4",
    	"h5",
    	"p"
    ],
    "plugins": [
        "fullscreen"
    ],
	"linkNewTab": true
}
```

**Comment by timkelty** [comment]
@jesuismaxime I thought it was related to `linkNewTab` as well, but actually seem to have determined a different cause (at least for me).

The content in question for me was something like this:

```
<p>Content goes <u><a href="https://google.com">here</a></u>.</p>
```

Apparently someone has switched to source and added the `<u>`.

Once that `<u>` is there, any changes made in the "edit link" popup don't persist on save, and you'll see the js error in the console.

Very weird! Not sure yet if this is a Redactor bug or something with htmlpurifier.

**Comment by andris-sevcenko** [comment]
Redactor has been since updated to 3.3.0. Can you check if this is still an issue for you? I'll reopen the issue if that's the case.
